### PR TITLE
Switch to generic alpine base

### PR DESCRIPTION
**Pull request by afwolfe**
Potentially addresses #10 and allows multiplatform builds by switching to a generic Alpine Linux base and installing Oracle OpenJDK via the package manager.
~It also improves security by running the application as a non-root user within the container.~ #12

As an alternative solution to #10, `11-jre` could be used for an Ubuntu base, but would increase the final image size:
```
REPOSITORY                        TAG               IMAGE ID       CREATED          SIZE
craumix/jmusicbot                 ubuntu            66df074b29fc   2 seconds ago    300MB    # eclipse-temurin:11-jre (Ubuntu base)
craumix/jmusicbot                 alpine            f143f661093d   11 minutes ago   214MB    # alpine:3 (this PR)
craumix/jmusicbot                 temurin           d0ec9a182942   11 minutes ago   198MB    # eclipse-temurin:11-jre-alpine (master)
```

### CODE REVIEW

**Comment by GavinL2001** [comment]
Thank you for fixing my oversight in #9. I do like the addition of a non-root user as well, and hope that this can get merged soon. I'll start testing this commit and report on any issues I encounter.

**Comment by GavinL2001** [comment]
While the image might be set as a non-root user, the container itself must still run as root in order to successfully load `JMusicBot.jar`. To fix this, I changed the following in my Dockerfile:

- Line 9: `RUN addgroup -S appgroup -g 1000 && adduser -S appuser -G appgroup -u 1000`

With that change, you can now specify the user in the docker-compose.yaml like so:
```
version: '2.2'

services:
  jmusicbot:
    image: craumix/jmusicbot
    container_name: jmusicbot
    restart: unless-stopped
    user: 1000:1000
    volumes:
     - ./config:/jmb/config
```
This way, the container should be able to fully run rootless without much issue. Other than that, the new changes seem to work well for me!

**Comment by afwolfe** [comment]
That's a good point about the UID/GID. Looks like the default in Alpine will be UID=100 and GID=101.
I thought this was a simple change at first, but to avoid scope creep, I'll pull those changes out and submit a separate PR for the non-root user. (#12)

**Comment by soguertler** [comment]
Should be solved with latest commit. Please let me know if you have any issues with my changes.

**Pull request closed without merging**
